package zyx.game.behavior;


public enum BehaviorType
{
	CHARACTER_ANIMATOR,
	CLIP_BOARD_VIEWING,
	CLIP_BOARD_DRAWING,
	FIRST_PERSON,
	ONLINE_POSITION,
	JIGGLE,
	ROTATE,
	CAMERA_FIRST_PERSON,
	PLAYER_MOVEMENT,
	CAMERA_LIGHT,
	CAMERA_FREE_FLY,
	CAMERA_UPDATE_VIEW;
}
